const swaggerJsdoc = require('swagger-jsdoc');
const swaggerUi = require('swagger-ui-express');
const options = {
    // List of files to be processed.
    apis: ['./routes/auth.route.js', './cookies/index.js'],
    // You can also set globs for your apis
    // e.g. './routes/*.js'
    basePath: '/',
    swaggerDefinition: {
        info: {
            description: 'Test API with autogenerated swagger doc',
            swagger: '2.0',
            title: 'Dessert API',
            version: '4.0.0',
        },
    },

};
const specs = swaggerJsdoc(options);

module.exports.specs;